# Generated by Django 4.1.2 on 2022-12-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokeMart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreObjeto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('lugar', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('fechaCompra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=40)),
                ('ataque_base_1', models.CharField(max_length=70)),
                ('ataque_especial_1', models.CharField(max_length=70)),
                ('dano_base', models.IntegerField()),
                ('defensa_base', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('Region', models.CharField(max_length=50)),
                ('nombre_objeto_mas_usado', models.CharField(max_length=80)),
                ('nombre_pokemon_favorito', models.CharField(max_length=60)),
                ('id_objeto_mas_usado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemart')),
                ('id_pokemon_favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemon')),
            ],
        ),
    ]
