# Generated by Django 4.1.3 on 2022-11-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=40)),
                ('ataque_base_1', models.CharField(max_length=70)),
                ('ataque_especial_1', models.CharField(max_length=70)),
                ('dano_base', models.IntegerField()),
                ('defensa_base', models.IntegerField()),
            ],
        ),
    ]
