# Generated by Django 4.1.3 on 2022-12-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('Region', models.CharField(max_length=50)),
                ('objeto_mas_usado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemart')),
                ('pokemon_favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
        ),
    ]
