# Generated by Django 4.1.3 on 2022-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemart_id_entrenador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='objeto_mas_usado',
            new_name='id_objeto_mas_usado',
        ),
        migrations.RenameField(
            model_name='entrenador',
            old_name='pokemon_favorito',
            new_name='id_pokemon_favorito',
        ),
        migrations.AddField(
            model_name='entrenador',
            name='nombre_objeto_mas_usado',
            field=models.CharField(default='pocion', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrenador',
            name='nombre_pokemon_favorito',
            field=models.CharField(default='Pikachu', max_length=60),
            preserve_default=False,
        ),
    ]
